version: "3.7"

services:
    app:
        container_name: app_sas
        build:
            args:
                user: macedo
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app #laravel9
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - backend_sas

    nginx:
        container_name: nginx_sas
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8955:80
            - 4455:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - backend_sas

    mysql:
        container_name: mysql_sas
        image: mysql/mysql-server:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - 33060:3306
        networks:
            - backend_sas

    redis:
        container_name: redis_sas
        image: redis:latest
        networks:
            - backend_sas

networks:
    backend_sas:
        driver: bridge
